<?php include("header.php");?>
    <body id="sys_background">
        <div class="ys_wrap">
           
           <?php include("menu.php"); ?>
        
            <div class="ys_header">
                <div class="ys_banner_wrap">
                    <div id="sys_banner">
                        <div class="ys_banner_over"></div>
                    </div>
                </div>
            </div>
            <div id="content">
               
            <table style="width: 100%; padding: 0px; margin: 0px; border-collapse: collapse" class="layout_2-column-right sys_layout">
    
        <tbody><tr id="layout_row1">
            <td id="sys_region_2" width="30%" style="margin:0px; padding:5px; vertical-align:top; line-height:normal; min-width:100px" class="zone_left"><div id="I47" style="display:block;clear: both;text-align:center;" class="Image_Default"><img id="I47_img" src="files/Swanmum Logo.jpg" style="width:244px; border:none;"></div></td>
            <td><div style="font-size:0px; width:5px"></div></td>
            <td id="sys_region_1" width="70%" style="margin:0px; padding:5px; vertical-align:top; line-height:normal; min-width:100px" class="zone_right"><div id="I46" style="display:block;clear: both;" class="Text_Default">    
    <div id="I46_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><h3><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span">Our mission:<br><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span">To provide excellent&nbsp;academic and&nbsp;accommodative&nbsp;services with parents and&nbsp;their&nbsp;children in mind.&nbsp;</span></span></h3> 
<h6><font class="Apple-style-span" color="#333333" face="&#39;Trebuchet MS&#39;, sans-serif"><span style="FONT-SIZE: x-large" class="Apple-style-span"><b><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, Arial, Helvetica, sans-serif; FONT-SIZE: 13px; FONT-WEIGHT: bold" class="Apple-style-span"><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51)"><span style="FONT-SIZE: x-large" class="Apple-style-span">The journey</span></span><span style="-webkit-border-horizontal-spacing: 2px; -webkit-border-vertical-spacing: 2px"><span style="FONT-SIZE: large" class="Apple-style-span">&nbsp;<span style="FONT-WEIGHT: normal" class="Apple-style-span">of seeking education in a foreign land is challenging due to cultural, psychological and physiological changes. Therefore, discerning parents find homestays a more attractive choice over hostels and&nbsp;dormitories,</span></span></span></span><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51)"><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span">&nbsp;knowing that&nbsp;their&nbsp;children will be well taken care of.&nbsp;</span></span></span></span></span></b></span></font></h6> 
<h6><font class="Apple-style-span" color="#333333" face="&#39;Trebuchet MS&#39;, sans-serif"><span style="FONT-SIZE: x-large" class="Apple-style-span"><b><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, Arial, Helvetica, sans-serif; FONT-SIZE: 13px; FONT-WEIGHT: bold" class="Apple-style-span"><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51)"><span style="FONT-SIZE: large" class="Apple-style-span"><span style="FONT-WEIGHT: normal" class="Apple-style-span">At Swanmum Homestay, more than just providing accommodation and food, we help to nurture our students to be champions of&nbsp;tomorrow.</span></span></span></span></span></span></b></span></font></h6></div>
    
</div><div id="I57" style="display:block;clear: both;text-align:center;" class="YouTube_Default">    
    <object width="425" height="350">
        <param name="movie" value="http://www.youtube.com/v/53kbymS6yE4">
        <param name="wmode" value="transparent">
        <param name="allowFullScreen" value="true">
        <param name="allowScriptAccess" value="always">
        <embed src="http://www.youtube.com/v/53kbymS6yE4" type="application/x-shockwave-flash" wmode="transparent" width="425" height="350" allowfullscreen="true" allowscriptaccess="always">
    </object>
    
</div><div id="I204" style="display:block;clear: both;" class="Text_Default">    
    <div id="I204_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span"><br></span>&nbsp;</p> 
<p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span">Our Location:<br></span><span style="font-family: &#39;Trebuchet MS&#39;,sans-serif; color: rgb(51, 51, 51); font-size: x-large; font-weight: bold;" class="Apple-style-span"><span style="font-size: large; font-weight: normal;" class="Apple-style-span">- <span style="font-weight: bold;">5 minutes walk to Tanah Merah MRT station</span></span></span></p><p><br><span style="font-family: &#39;Trebuchet MS&#39;,sans-serif; color: rgb(51, 51, 51); font-size: x-large; font-weight: bold;" class="Apple-style-span"><span style="font-size: large; font-weight: normal;" class="Apple-style-span"><span style="font-weight: bold;"></span></span></span></p></div>
    
</div><div id="I242" style="display:block;clear: both;text-align:left;" class="Image_Default"><img id="I242_img" src="files/Swanmum Tanah Merah Map.jpg.opt620x418o0,0s620x418.jpg" style="width:620px; border:none;"></div><div id="I243" style="display:block;clear: both;" class="Text_Default">    
    <div id="I243_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span"><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span"><span style="font-weight: bold;"></span></span></span><span style="font-family: &#39;Trebuchet MS&#39;,sans-serif; color: rgb(51, 51, 51); font-size: x-large; font-weight: bold;" class="Apple-style-span"><span style="font-size: large; font-weight: normal;" class="Apple-style-span"><span style="font-family: &#39;Trebuchet MS&#39;,sans-serif; color: rgb(51, 51, 51); font-size: x-large; font-weight: bold;" class="Apple-style-span"><br></span></span></span></p><p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span"><span style="FONT-SIZE: large; FONT-WEIGHT: normal" class="Apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, sans-serif; COLOR: rgb(51,51,51); FONT-SIZE: x-large; FONT-WEIGHT: bold" class="Apple-style-span">Some of our nearby schools:</span></span></span></p>
</div>
    
</div><div id="I203" style="display:block;clear: both;" class="Layout1_Default"><table border="0" cellspacing="0" cellpadding="0" style="width:100%;"><tbody><tr><td id="Left_I203" style="text-align:left; vertical-align:top; width:50%;"><div id="I208" style="display:block;clear: both;" class="Text_Default">    
    <div id="I208_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; mso-bidi-font-size: 18.0pt"><font size="3">  
<p><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"><strong><font class="Apple-style-span" color="#006600">Primary Schools</font> </strong></span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"><br><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;">Pasir Ris</span></em></span><span style="FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt"></span></p></font></span><font size="3"> 
<p><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">- Casuarina Primary School</span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"><br><span class="apple-style-span">- Coral Primary School</span><br><span class="apple-style-span">- Elias Park Primary School</span><br><span class="apple-style-span">- Loyang Primary School</span><br><span class="apple-style-span">- Meridian Primary School</span><br><span class="apple-style-span">- Park View Primary School</span><br><span class="apple-style-span">- Pasir Ris Primary School</span><br><span class="apple-style-span">- White Sands Primary School</span></span></p> 
<p><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">Tampines</span></em>  
</p><p><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">- Changkat Primary School</span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"><br><span class="apple-style-span">- Chongzheng Primary School</span><br><span class="apple-style-span">- East Spring Primary School</span><br><span class="apple-style-span">- East View Primary School</span><br><span class="apple-style-span">- Gongshang Primary School</span><br><span class="apple-style-span">- Griffiths Primary School</span><br><span class="apple-style-span">- Junyuan Primary School</span><br><span class="apple-style-span">- Poi Ching School</span><br><span class="apple-style-span">- Qiaonan Primary School</span><br><span class="apple-style-span">- St. Hilda's Primary School</span><br><span class="apple-style-span">- Tampines North Primary School</span><br><span class="apple-style-span">- Tampines Primary School</span><br><span class="apple-style-span">- Yumin Primary School</span></span><span style="FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt"></span></p></font></span><font size="3"> 
<p><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">Bedok</span></em></p> 
<p><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"></span></em><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">- </span></em><span class="apple-style-span"><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt">Bedok Green Primary School</span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 18.0pt"><br><span class="apple-style-span">- Bedok West Primary School</span><br><span class="apple-style-span">- CHIJ (Katong) Primary</span><br><span class="apple-style-span">- Damai Primary School</span><br><span class="apple-style-span">- East Coast Primary School</span><br><span class="apple-style-span">- Fengshan Primary School</span><br><span class="apple-style-span">- Opera Estate Primary School</span><br><span class="apple-style-span">- Red Swastika School</span><br><span class="apple-style-span">- St. Anthony's Canossian Primary School</span><br><span class="apple-style-span">- St. Stephen's School</span><br><span class="apple-style-span">- Telok Kurau Primary School</span><br><span class="apple-style-span">- Temasek Primary School</span><br><span class="apple-style-span">- Yu Neng Primary&nbsp; School</span></span><span class="apple-style-span"><b><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 20pt; mso-bidi-font-size: 24.0pt"></span></b></span></p><b></b> 
<p><span style="LINE-HEIGHT: 150%; FONT-SIZE: 10pt; mso-bidi-font-size: 12.0pt"><font color="#000000"></font>&nbsp;</span></p> 
<p><span class="apple-style-span"><b><span style="font-family: &#39;Trebuchet MS&#39;, sans-serif; font-size: 14pt; "><font class="Apple-style-span" color="#006600">Junior College</font></span></b></span><span class="apple-style-span"><span style="font-family: &#39;Trebuchet MS&#39;, sans-serif; font-size: 14pt; "><font class="Apple-style-span" color="#003300"> </font></span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt"><br><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;">Pasir Ris</span></em></span></p><em></em> 
<p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt"><font color="#000000">- Meridian Junior College</font></span></p> 
<p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt"></span><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt">Tampines<br></span></em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt"><font color="#000000">- Tampines Junior College</font></span></p> 
<p style="MARGIN: 0in 0.3in 0pt 0in"><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt"><font color="#000000">Bedok<br>- </font></span></i><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt"><font color="#000000">Temasek Junior College</font></span><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Verdana&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-fareast-font-family: &#39;Times New Roman&#39;"> 
</span></i></p><i style="mso-bidi-font-style: normal"></i></font><p>&nbsp;</p></div>
    
</div></td><td id="Right_I203" style="vertical-align:top; width:50%;"><div id="I209" style="display:block;clear: both;" class="Text_Default">    
    <div id="I209_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><p><font class="Apple-style-span" color="#446600">&nbsp;</font><span class="apple-style-span"><span style="font-family: &#39;Trebuchet MS&#39;, sans-serif; font-size: 14pt; "><strong><font class="Apple-style-span" color="#006600">Secondary Schools</font></strong><font class="Apple-style-span" color="#446600"> </font></span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><br><em><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;">Pasir Ris</span></em></span></p><em></em> 
<p><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">- Coral Secondary School<br>- Greenview Secondary School<br>- Hai Sing Catholic School<br>- Loyang Secondary School<br>- Pasir Ris Crest Secondary School<br><i style="mso-bidi-font-style: normal">- </i>Siglap<i style="mso-bidi-font-style: normal"> </i>Secondary School</font></span></p> 
<p style="MARGIN: 0in 0.3in 0pt 0in"><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">Tampines</font></span></i></p><i style="mso-bidi-font-style: normal"><font color="#000000"></font></i> 
<p><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">- Duman Secondary School<br>- East Spring Secondary School<br>- East View Secondary School<br>- JunYuan Secondary School<br>- Ngee Ann Secondary School<br>- Pasir Ris Secondary School<br>- Saint Hilda’s Secondary School<br>- Sprindfield Secondary School<br>- Tampines Secondary School </font></span></p><font color="#000000"></font> 
<p><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">Simei<br></font></span></i><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">- Changkat Secondary School</font></span></p> 
<p style="MARGIN: 0in 0.3in 0pt 0in"><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">Bedok</font></span></i> 
</p><p style="MARGIN: 0in 0.3in 0pt 0in"><i style="mso-bidi-font-style: normal"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">- </font></span></i><span style="LINE-HEIGHT: 150%; FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; FONT-SIZE: 14pt; mso-bidi-font-size: 12.0pt"><font color="#000000">Anglican High School<br>- Bedok Green Secondary School<br>- Bedok North Secondary School<br>- Bedok South Secondary School<br>- Bedok Town Secondary School<br>- Bedok View Secondary School<br>- Chai Chee Secondary School<br>- Damai Secondary School<br>- Saint Anthony’s Canossian Secondary School<br>- Tampines Secondary School<br>- Temasek Secondary School</font></span></p><font color="#000000"></font> 
<p>&nbsp;</p> 
<p><span class="apple-style-span"><b><span style="font-family: &#39;Trebuchet MS&#39;, sans-serif; font-size: 14pt; "><font class="Apple-style-span" color="#006600">Polytechnic</font></span></b></span><span class="apple-style-span"><span style="font-family: &#39;Trebuchet MS&#39;, sans-serif; font-size: 14pt; "><font class="Apple-style-span" color="#009900">&nbsp;</font></span></span><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt"><br><em>Tampines/Bedok</em></span></p> 
<p><span style="FONT-FAMILY: &#39;Trebuchet MS&#39;, &#39;sans-serif&#39;; COLOR: #333333; FONT-SIZE: 14pt">- Temasek Polytechnic</span></p></div>
    
</div></td></tr></tbody></table></div></td>
        </tr>
    </tbody></table>


            </div>
			
            <div class="ys_bottom"></div>
        </div>
    
</body></html>