<?php include("header.php");?>

				<BODY id="sys_background">
					<DIV class="ys_wrap">
<?php include("menu.php"); ?>
<DIV class="ys_header">
	<DIV class="ys_banner_wrap">
		<DIV id="sys_banner">
			<DIV class="ys_banner_over"></DIV></DIV></DIV></DIV>
<DIV id="content">
	<DIV class="layout_1-column sys_layout" style="margin: 0px; padding: 0px; width: 100%;">
		<DIV id="layout_row1">
			<DIV class="zone_top" id="sys_region_1" style="margin: 0px; padding: 5px; line-height: normal; vertical-align: top; min-width: 100px;">
				<DIV class="Layout1_Default" id="I233" style="clear: both; display: block;">
			
			
			<table border="0" cellspacing="0" cellpadding="0" style="width:100%;"><tr><td id="Left_I112" style="text-align:left; vertical-align: top; width:31.10403397027601%;" ><div id="I43" style="display:block;clear: both;" class="Text_Default">
    <div id="I43_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;">

<h3 style="text-align: center;">
<A href="index.php?lang=en">
<FONT color=#990000>EN</FONT></A>
<A href="index.php?lang=sc">
<FONT color=#990000>简</FONT></A>
<A href="index.php?lang=tc">
<FONT color=#990000>繁</FONT></A>

</h3></div>
    
</div><div id="I1" style="display:block;clear: both;text-align:center;" class="Image_Default"><img id="I1_img" src="files/pct_education_page02.jpg " style='width:250px; border:none;'/></div><div id="I2" style="display:block;clear: both;text-align:center;" class="Image_Default"> <img id="I2_img" src="files/istock_4641886.jpg" style='width:249px; border:none;'/></div><div id="I71" style="display:block;clear: both;text-align:center;" class="Widgetbox_Default">
</div></td><td id="Right_I112" style="vertical-align:top; width:68.895966029724%;" ><div id="I76" style="display:block;clear: both;" class="Text_Default">
    <div id="I76_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><p><font class="Apple-style-span" color="#336633" size="7" face="楷体, serif"><span style="FONT-SIZE: 27px" class="Apple-style-span"><b><span class="apple- style-span"><b><span style="line-height: 150%; font-family: 宋体; font-size: 20pt; " lang="ZH-TW">
<font class="Apple-style- span" color="#990000">新加坡教育</font></span></b></span>
<span class="apple-converted-space"><b><span style="-webkit-border-horizo​​ntal-spacing: 0px; -webkit-border-vertical-spacing: 0px"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 10pt; mso- bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA">&nbsp;</span></span></b></span></b></span></font></p>
<p><font class="Apple-style-span" color="#336633" size="7" face="楷体, serif"><span style="FONT-SIZE: 27px" class="Apple-style -span"><span class="apple-converted-space"><span style="-webkit-border-horizo​​ntal-spacing: 0px; -webkit-border-vertical-spacing: 0px"><span style="LINE -HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 10pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast- language: ZH-TW; mso-bidi-language: AR-SA"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: # 021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR- SA" lang="ZH-TW">新加坡的地理位置在东南亚的正中心，也是欧，亚，澳之间的桥梁，因为拥有良好的地理位置和高级的基础设施，新加坡已发展成为一个商业和教育并重的主要枢纽。 </span></span></span></span></span></span></font></p>
<p><font class="Apple-style-span" color="#336633" size="7" face="楷体, serif"><span style="FONT-SIZE: 27px" class="Apple-style -span"><span class="apple-converted-space"><span style="-webkit-border-horizo​​ntal-spacing: 0px; -webkit-border-vertical-spacing: 0px"><span style="LINE -HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: black; FONT-SIZE: 10pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast- language: ZH-TW; mso-bidi-language: AR-SA"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: # 021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR- SA" lang="ZH-TW"></span></span></span></span></span></span></font></p><font class="Apple-style -span" color="#336633" size="7" face="楷体, serif">
<p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast- language: ZH-TW" lang="ZH-TW">目前新加坡有大约</span></span><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR : #021324; FONT-SIZE: 16pt; mso-fareast-language: ZH-TW">70,000<span lang="ZH-TW">名外籍学生在这里就读，新加坡政府进一步发布消息表示在</span> 5<span lang="ZH-TW">年内，外籍学生人数将增长到</span>150,000<span lang="ZH-TW">。 <br><br></span></span></span></p></font></div>
    
</div><div id="I113" style="display:block;clear: both;text-align:center;" class="YouTube_Default">
 	  <?php include("indexvideo.php"); ?>
    
</div><div id="I114" style="display:block;clear: both;" class="Text_Default">
    <div id="I114_sys_txt" class="sys_txt" style="margin:0px; padding:0px; color:; font:; background-color:;"><p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast-language: ZH-TW"><span lang="ZH- TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso-ansi-language: EN-US; mso-fareast-language : ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><br><font class="Apple-style-span" color="#990000">为什么父母会选择新加坡？ </font></span></strong></span></span></span><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: # 021324; FONT-SIZE: 16pt; mso-fareast-language: ZH-TW"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW ; mso-bidi-language: AR-SA"><br>1)<span lang="ZH-TW">安全的国家</span>&nbsp;</span></strong><b><span style ="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA"><br></span></b><span class="apple-style-span"><span style="LINE -HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast -language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span style="FONT-WEIGHT: normal" class="Apple-style-span">当父母送他们的孩子来新加坡读书时，他们能完全的放心，因为新加坡是一个高度安全和政治稳定的国家。 </span></span></span></span></strong></span></span></span></p>
<p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast- language: ZH-TW"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN- US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span style="FONT-WEIGHT: normal" class="Apple-style-span" ><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-ansi-language: EN-US; mso-fareast-language: ZH -TW; mso-bidi-language: AR-SA">2)<span lang="ZH-TW">高品质的教育</span></span></strong><span style="LINE-HEIGHT : 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language : ZH-TW; mso-bidi-language: AR-SA"><br></span><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY : 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso- bidi-language: AR-SA" lang="ZH-TW">我们的文凭都是全球认可的，在新加坡毕业后拿到的文凭适合前去欧洲，美国或澳洲继续读书。 </span></span></span></span></span></span></strong></span></span></span></p>
<p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast- language: ZH-TW"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN- US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span style="FONT-WEIGHT: normal" class="Apple-style-span" ><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><strong><span style ="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi- language: AR-SA">3)<span lang="ZH-TW">高品质的生活</span></span></strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY : 宋体; COLOR: #497f49; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso- bidi-language: AR-SA"><br></span><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333 ; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA " lang="ZH-TW">根据</span><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family : 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA">2008<span lang="ZH-TW">年，美世人力资源咨询公司的调查，在亚洲，新加坡的生活品质领先其他国家，并在世界上排名</span>32<span lang="ZH-TW">，拥有世界第一流的技术和基础设施，使我们处在全球的尖端。 </span></span></span></span></span></span></span></span></span></strong></span></span></ span></p>
<p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast- language: ZH-TW"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN- US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span style="FONT-WEIGHT: normal" class="Apple-style-span" ><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple -style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA"><span lang="ZH-TW"><strong><span style="LINE- HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR- SA">4)<span lang="ZH-TW">新加坡精通英文和中文</span></span></strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language : AR-SA"><br><span class="apple-style-span"><span lang="ZH-TW">在双语环境中生活和学习，让学生接触到英语和中文这</span >2<span lang="ZH-TW">种世界上最常用的语言。这将使他们未来进入社会有足够的竞争能力。 </span></span></span></span></span></span></span></span></span></span></span></span></ strong></span></span></span></p>
<p style="MARGIN: 0in 0in 12pt"><span class="apple-style-span"><span style="FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-fareast- language: ZH-TW"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #497f49; FONT-SIZE: 20pt; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN- US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span style="FONT-WEIGHT: normal" class="Apple-style-span" ><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA" lang="ZH-TW"><span class="apple -style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #333333; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso -ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA"><span lang="ZH-TW"><span style="LINE-HEIGHT: 150 %; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH -TW; mso-bidi-language: AR-SA"><span class="apple-style-span"><span lang="ZH-TW"><strong><span style="LINE-HEIGHT: 150% ; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA">5 )<span lang="ZH-TW">许多种族和文化的结合</span></span></strong><b><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language : AR-SA"><br></span></b><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: # 021324; FONT-SIZE: 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR- SA" lang="ZH-TW">随着</span></span><span class="apple-converted-space"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE: 16pt; mso-bidi-font-family: 宋体; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA ">&nbsp;</span></span><span class="apple-style-span"><span style="LINE-HEIGHT: 150%; FONT-FAMILY: 宋体; COLOR: #021324; FONT-SIZE : 16pt; mso-bidi-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: ZH-TW; mso-bidi-language: AR-SA">51<span lang="ZH-TW">个不同的种族和睦相处，这个国家成为一个让学生体验不同生活习俗的平台。 </span></span></span></span></span></span></span></span></span></span></span></span></ span></span></span></strong></span></span></span></p>
<p>&nbsp;</p></div>
    
</div></td></tr></table>
			
			</DIV>
	<DIV class="HTML_Default" id="I168" style="text-align: left; clear: both; display: block;">
	</DIV></DIV></DIV></DIV></DIV>
			<DIV class="ys_bottom"></DIV></DIV>


	</BODY></HTML>
